export const ORDER_REQUEST: 'ORDER_REQUEST' = 'ORDER_REQUEST';
export const ORDER_SUCCESS: 'ORDER_SUCCESS' = 'ORDER_SUCCESS';
export const ORDER_FAILED: 'ORDER_FAILED' = 'ORDER_FAILED';
export const ORDER_DETAILS_CLOSE: 'ORDER_DETAILS_CLOSE' = 'ORDER_DETAILS_CLOSE';
