export const AUTH_CHECKED: 'AUTH_CHECKED' = 'AUTH_CHECKED';
export const SET_USER: 'SET_USER' = 'SET_USER';
export const USER_REQUEST: 'USER_REQUEST' = 'USER_REQUEST';
export const USER_REQUEST_FAILED: 'USER_REQUEST_FAILED' = 'USER_REQUEST_FAILED';
export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS' =
  'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILED: 'LOGOUT_REQUEST_FAILED' =
  'LOGOUT_REQUEST_FAILED';
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS' =
  'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED' =
  'LOGIN_REQUEST_FAILED';
export const PATCH_USER_REQUEST: 'PATCH_USER_REQUEST' = 'PATCH_USER_REQUEST';
export const PATCH_USER_REQUEST_FAILED: 'PATCH_USER_REQUEST_FAILED' =
  'PATCH_USER_REQUEST_FAILED';
export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' =
  'FORGOT_PASSWORD_REQUEST';
export const SET_EMAIL_CORRECT_FLAG: 'SET_EMAIL_CORRECT_FLAG' =
  'SET_EMAIL_CORRECT_FLAG';
export const FORGOT_PASSWORD_REQUEST_FAILED: 'FORGOT_PASSWORD_REQUEST_FAILED' =
  'FORGOT_PASSWORD_REQUEST_FAILED';
export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' =
  'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_SUCCESS: 'RESET_PASSWORD_REQUEST_SUCCESS' =
  'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILED: 'RESET_PASSWORD_REQUEST_FAILED' =
  'RESET_PASSWORD_REQUEST_FAILED';
